In [1]:
import requests as rq
import bs4 as bs4
import time
import json
import pandas as pd
import numpy as np
import math
import time

# Minerando dados Editoras

In [2]:
# Url onde estão todas as editoras

url_editoras = 'https://www.skoob.com.br/editoras/'

In [3]:
# Fazendo request do link e transformando em um objeto do bs4

response = rq.get(url_editoras)
pagina_html = bs4.BeautifulSoup(response.text)

In [4]:
# Procurando tags

tags = pagina_html.findAll(id="resultadoBusca-")
editoras = tags[0].findAll('strong')

lista_editoras = []
lista_links = []

for x in editoras:
    if x.find('a') != None:
        editora = x.get_text()
        lista_editoras.append(editora)
        
        link = x.find('a').get('href')
        lista_links.append(link)
        
livros_editora = []
numero_livros = tags[0].findAll('span')

for livros in range(1, len(numero_livros), 8):
    n_livros = numero_livros[livros].get_text().split()[0]
    n_livros = n_livros.replace('.', '')
    livros_editora.append(n_livros)

In [5]:
# Criando dataframe que armazenará os dados

df = pd.DataFrame()
df['editora'] = lista_editoras
df['link'] = lista_links
df['qtde_livros'] = livros_editora

In [6]:
df

                 editora                               link qtde_livros
0             Intrínseca             /editora/11-intrinseca        1410
1               Sextante               /editora/19-sextante        1416
2               Arqueiro               /editora/21-arqueiro         656
3          Galera Record          /editora/25-galera-record         876
4                  Rocco                  /editora/41-rocco        3536
5          Melhoramentos          /editora/51-melhoramentos        2057
6              Valentina              /editora/64-valentina         108
7              Gutenberg              /editora/73-gutenberg         240
8                  Verus                  /editora/98-verus         520
9   HarperCollins Brasil  /editora/100-harpercollins-brasil         467
10   Universo dos Livros   /editora/102-universo-dos-livros         850
11         Universo Geek         /editora/121-universo-geek          26
12  The Gift Box Editora  /editora/135-the-gift-box-editora         127
13             Excelsior             /editora/136-excelsior          42
14         Martin Claret         /editora/141-martin-claret         348

In [7]:
# Função para ser aplicada em cada linha do dataframe na coluna código
# Parâmetro x: string -> link da editora
# Irá retornar o código da editora

def codigo(x):
    return x.split('/')[-1].split('-')[0]

codigos = df['link'].apply(codigo)
df['codigo'] = codigos

In [8]:
df

                 editora                               link qtde_livros codigo
0             Intrínseca             /editora/11-intrinseca        1410     11
1               Sextante               /editora/19-sextante        1416     19
2               Arqueiro               /editora/21-arqueiro         656     21
3          Galera Record          /editora/25-galera-record         876     25
4                  Rocco                  /editora/41-rocco        3536     41
5          Melhoramentos          /editora/51-melhoramentos        2057     51
6              Valentina              /editora/64-valentina         108     64
7              Gutenberg              /editora/73-gutenberg         240     73
8                  Verus                  /editora/98-verus         520     98
9   HarperCollins Brasil  /editora/100-harpercollins-brasil         467    100
10   Universo dos Livros   /editora/102-universo-dos-livros         850    102
11         Universo Geek         /editora/121-universo-geek          26    121
12  The Gift Box Editora  /editora/135-the-gift-box-editora         127    135
13             Excelsior             /editora/136-excelsior          42    136
14         Martin Claret         /editora/141-martin-claret         348    141

In [9]:
# Dataframe com as editoras

df.to_csv('./editoras_link.csv', index=False)

# Minerando livros e link de cada editora

Os livros de cada editora estão no link : "https://www.skoob.com.br/editora/livros/codigoDeCadaEditora"  
É necessário o código de cada editora para entrar na página dos livros. Os códigos foram salvos no editoras_link.csv

In [11]:
lista_livros = []
lista_livros_link = []

for index, row in df.iterrows():
    print('--------------------------')
    print(df['editora'][index])
    
    
    url_base = 'https://www.skoob.com.br/editora/livros/{}/mpage:{}'
    
    # Número de páginas com livros
    # Cada página do site mostra 40 livros
    n_page = math.ceil(int(df['qtde_livros'][index])/40) + 1
    
    for x in range(1, n_page):
        print(x)
        url_livros = url_base.format(df['codigo'][index], x)
        
        response = rq.get(url_livros)
        pagina_html = bs4.BeautifulSoup(response.text)
        
        lista_div = pagina_html.findAll("div", {"class": "box_livro"})
        
        for x in lista_div:
            titulo = x.find('h3').get_text()
            link = x.find('a').get('href')
            
            lista_livros.append(titulo)
            lista_livros_link.append(link)
        
        #time.sleep(1)

--------------------------
Intrínseca
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
--------------------------
Sextante
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
--------------------------
Arqueiro
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
--------------------------
Galera Record
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
--------------------------
Rocco
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
--------------------------
Melhoramentos
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
--------------------------
Valentina
1
2
3
--------------------------
Gutenberg
1
2
3
4
5
6
--------------------------
Verus
1
2
3
4
5
6
7
8
9
10
11
12
13
--------------------------
HarperCollins Brasil
1
2
3
4
5
6
7
8
9
10
11
12
--------------------------
Universo dos Livros
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
--------------------------
Universo Geek
1
--------------------------
The Gift Box Editora
1
2
3
4
--------------------------
Excelsior
1
2
--------------------------
Martin Claret
1
2
3
4
5
6
7
8
9

In [12]:
# Criando dataframe

df = pd.DataFrame()
df['livros'] = lista_livros
df['link'] = lista_livros_link

In [13]:
df

,livros,link
0,Orçamento sem falhas,/orcamento-sem-falhas-11677985ed11693528.html
1,O Enigma do Quarto 622,/o-enigma-do-quarto-622-11693957ed11707901.html
2,A Segunda Vida de Missy,/a-segunda-vida-de-missy-11665021ed11726704.html
3,As Sombras do Mal,/as-sombras-do-mal-11729572ed11740782.html
4,"Leopardo Negro, Lobo Vermelho",/leopardo-negro-lobo-vermelho-11785663ed117421...
...,...,...
12686,Poesia de Álvaro de Campos,/poesia-de-alvaro-de-campos-26706ed55518.html
12687,Ben-Hur,/ben-hur-538ed23492.html
12688,Folhas de Relva,/folhas-de-relva-274ed376.html
12689,Espumas Flutuantes,/espumas-flutuantes-1218ed11828493.html
12690,O sermão da montanha,/o-sermao-da-montanha-6056ed11671460.html

In [14]:
# Dataframe com as editoras

df.to_csv('./livros_link.csv', index=False)

# Livros

In [15]:
df = pd.read_csv('./livros_link.csv')

In [ ]:
info_livros = []

for index, row in df.iterrows():
    
    livro = {}
    
    # De 10 em 10 request espera 1 segundo
    if index % 10 == 0:
        time.sleep(1)
    
    
    try:
        # Request para a paǵina do livro
        url_base = 'https://www.skoob.com.br{}'.format(df['link'][index])        
        response = rq.get(url_base)
        pagina_html = bs4.BeautifulSoup(response.text)
        
        # Titulo
        div_lateral = pagina_html.find("div", {"id": "pg-livro-menu-principal"})
        livro['titulo'] = div_lateral.find('strong').get_text()

        #print(f'{index} - {titulo}')
        #print(url_base)
        
        # Autor
        livro['autor'] = div_lateral.findAll('a')[1].get_text()
        
        # ISBN 
        div_menor = div_lateral.find('div', {"class": "sidebar-desc"})
        isbns = div_menor.findAll('span')
        try:
            livro['ISBN_13'] = str(isbns[0]).split('>')[1].split('<')[0]
            livro['ISBN_10'] = str(isbns[1]).split('>')[1].split('<')[0]
        except:
            livro['ISBN_13'] = ''
            livro['ISBN_10'] = ''
            
        
        # Texto com dados
        texto = div_menor.get_text()
        
        try:    
            livro['ano'] = texto.split('Ano: ')[1].split(' ')[0]
        except:
            livro['ano'] = ''
        
        try:
            livro['paginas'] = texto.split('Páginas: ')[1].split(' ')[0]
        except:
            livro['paginas'] = ''
            
        try:
            livro['idioma'] = texto.split('Idioma: ')[1].split(' ')[0]
        except:
            livro['idioma'] = ''
        
        try:
            livro['editora'] = texto.split('Editora: ')[1].split(' ')[0]
        except:
            livro['editora'] = ''
            

        div_superior = pagina_html.find('div', {'id': 'livro-perfil-status'})
        
        try:
             livro['rating'] = div_superior.find('span', {'class': 'rating'}).get_text()
        except:
             livro['rating'] = ''
        
        try:
            livro['avaliacao'] = div_superior.find('div', {'id': 'pg-livro-box-rating-avaliadores-numero'}).get_text().split(' ')[0]
        except:
            livro['avaliacao'] = ''


        info = div_superior.findAll('a', {'class': 'text_blue'})
        
        try:
            livro['resenha'] = info[0].get_text()
        except:
            livro['resenha'] = ''
            
        try:
            livro['abandonos']  = info[1].get_text()
        except:
            livro['abandonos'] = ''
        
        try:
            livro['relendo']  = info[2].get_text()
        except:
            livro['relendo'] = ''
            
        try:   
            livro['querem_ler'] = info[3].get_text()
        except:
            livro['querem_ler'] = ''
        
        try:
            livro['lendo'] = info[4].get_text()
        except:
            livro['lendo'] = ''
            
        try:
            livro['leram'] = info[5].get_text()
        except:
            livro['leram'] = ''


        info = pagina_html.find('p', {'itemprop': 'description'})
        
        try: 
            descricao = info.get_text().replace('\n', '')
            descricao = descricao.split('.')
            genero = descricao[-1]
            descricao = ''.join(descricao[:-1])
            livro['descricao'] = descricao
            livro['genero'] = genero
        except:
            livro['descricao'] = ''
            livro['genero'] = ''
            
        
        try: 
            info = pagina_html.find('span', {'class': 'pg-livro-icone-male-label'})
            livro['male'] = int(info.get_text().replace('%', ''))

            info = pagina_html.find('span', {'class': 'pg-livro-icone-female-label'})
            livro['female'] = int(info.get_text().replace('%', ''))
        
        except: 
            livro['male'] = 0
            livro['female'] = 0
            
        info_livros.append(livro)
        
    except Exception as e:
        print(e)
        continue

'NoneType' object has no attribute 'find'
'NoneType' object has no attribute 'find'
'NoneType' object has no attribute 'find'
'NoneType' object has no attribute 'find'

In [ ]:
# Algumas páginas possuem um formato diferente para mostrar o nome do autor
# As instâncias que estão com erro possuem autor como : \nR$ \n

for index, row in dd.iterrows():
    
    # Verificando se autor está errado
    if dd['autor'][index] == '\nR$ \n':
        
        livro = dd['titulo'][index]
        link = df[df['livros'] == livro].reset_index()
        
        try:
            url_base = 'https://www.skoob.com.br{}'.format(link['link'][0])
            response = rq.get(url_base)
            pagina_html = bs4.BeautifulSoup(response.text)
        except:
            continue
        
        try:
            autor = pagina_html.find("i", {"class": "sidebar-subtitulo"}).get_text()
        except:
            autor = ''
            print(url_base)
            
        dd.at[index, 'autor'] = autor
        print(autor)

In [ ]:
# Salvando dataset atualizado

dd.to_csv('./dados.csv', index=False)

In [ ]:
# Alguns livros possuem outro formato no nome do autor
# +/- 25 livros, vou apenas dropar esses registros

linhas_drop = df[df['autor'] == '\nR$ \n'].index
df.drop(index= linhas_drop, inplace=True)
df.to_csv('dados_ok_2.csv', index=False)

# Organizando dados

In [ ]:
# Verificar linhas vazias em cada coluna

for x in df.columns:

    nan_rows = df[df[x].isnull()]
    print(f"Número de linhas vazias na coluna: {x} = {nan_rows.shape[0]}")

In [ ]:
# Carregando datasets

livros_link = pd.read_csv('./livros_link.csv')
df = pd.read_csv('dados.csv')

In [ ]:
# Correção dos dados faltantes da coluna de autores

for index, row in df[df['autor'].isnull()].iterrows():
    
    livro = df['titulo'][index]
    link = livros_link[livros_link['livros'] == livro].reset_index()
    url_base = 'https://www.skoob.com.br{}'.format(link['link'][0])
    
    response = rq.get(url_base)
    pagina_html = bs4.BeautifulSoup(response.text)
    
    try:
        autor = pagina_html.find("h3", {"class": "secao-subtitulo"}).get_text()
    except:
        autor = ''
        
    df.at[index, 'autor'] = autor
    print(autor)

# Salvando dataset com dados novos
df.to_csv('./dados.csv', index=False)

In [ ]:
# Corrigindo ISBN
# Transformando dado em str

df['ISBN_10'] = df['ISBN_10'].astype('str')
df['ISBN_13'] = df['ISBN_13'].astype('str')

for index, row in df.iterrows():
    
    try:
        # Removendo .
        df.at[index, 'ISBN_13'] = df['ISBN_13'][index].split('.')[0]
    except:
        pass

In [ ]:
# Transformando ano em um inteiro

def to_int(x):
    try:
        return int(x)
    except:
        return(0)

df['ano'] = df['ano'].apply(to_int)

In [ ]:
# Corrigindo tipo das variáveis

df['paginas'] = df['paginas'].apply(to_int)
df['idioma'] = df['idioma'].astype('str')
df['avaliacao'] = df['avaliacao'].astype('int')
df['resenha'] = df['resenha'].astype('int')
df['abandonos'] = df['abandonos'].astype('int')
df['relendo'] = df['relendo'].astype('int')
df['querem_ler'] = df['querem_ler'].astype('int')
df['lendo'] = df['lendo'].astype('int')
df['leram'] = df['leram'].astype('int')
df['descricao'] = df['descricao'].astype('str')
df['genero'] = df['genero'].astype('str')
df['editora'] = df['editora'].astype('str')

In [ ]:
# Salvando dataset final

df.to_csv('./dados.csv', index=False)